const mongoose = require('mongoose');

const UserSchema = mongoose.Schema({
    username:{
        type:String,
        required:true,
    },
    surname:{
        type:String,
        required:true
    },
    profile_pic:{
        type:String,
        required:true,
        default:"https://pbs.twimg.com/media/BtFUrp6CEAEmsml.jpg"
    },
    cover_pic:{
        type:String,
        default:""
    },
    mobile:{
        type:Number,
    },
    email:{
        type:String,
        required:true 
    },
    password:{
        type:String,
        required:true
    },
    day:{
        type:String,
        required:true,
    },
    month:{
        type:String,
        required:true,
    },
    year:{
        type:String,
        required:true,
    },
    gender:{
        type:String,
        default:"male"
    },
    following:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    }],
    followers:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    }],
    createdAt:{
        type:Date,
        default:Date.now
    }
})

module.exports = mongoose.model('user' , UserSchema);